name: restlib_server
description: A sample command-line application
dependencies:
  crypto: any
  mime: any
  restlib_common:
    git: https://code.google.com/p/dart-restlib.common/
  restlib_core: any
dev_dependencies:
  restlib_testing:
    git: https://code.google.com/p/dart-restlib.testing/
  unittest: any
